services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file:
      - ./.env
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    env_file:
      - ./.env
    depends_on:
      - mongo
